### PR TITLE
Remove cocoapods

### PR DESCRIPTION
**Pull request by xavierLowmiller**
## Description

(Addresses #140)

This pull request removes Cocoapods in favor of Swift Package Manager.

There are 2 points missing from the issue:
- SwiftLint. As mentioned, users could have SwiftLint installed locally and rely on the GitHub action to make sure PRs are clean
- Licenses. [LicensePlist](https://github.com/mono0926/LicensePlist) supports SPM, but I'm unsure how to best integrate this into the pipeline.

## Checklist
- [x] Update `README.md`, if necessary 
  (e.g. when adding a new dependency, updating Swift Version, adding new language support)
- [ ] Add an entry (formatted like the others) on Upcoming Release in `CHANGELOG.md`

### CODE REVIEW

**Comment by fbernutz** [comment]
Thanks for this! I pushed two commits, one to fix the pipeline and one to remove Cocoapods from Gemfile. I hope you don't mind :) Running the tests locally now suceeds. There is still something wrong/missing in the CI.

Running Swiftlint with a user installation is fine for me 👍 For using LicensePlist you could peek to the setup in [CriticalMaps iOS](https://github.com/criticalmaps/criticalmaps-ios).

**Comment by fbernutz** [comment]
There was a [known issue](https://github.com/fastlane/fastlane/issues/15454#issuecomment-543761561) from Fastlane, that actions didn't wait for Xcode to resolve the packages, but they said it's fixes with 1.141.0, which we currently use.... 

Maybe adding these lines `sh "xcodebuild -resolvePackageDependencies"` in Fastfile will fix the CI. I'll try that later or you could try it.

**Comment by xavierLowmiller** [comment]
Thanks for the commits!

I’ll look into why the tests fail later today.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by xavierLowmiller** [comment]
I'm unsure where to place the LicensePlist job. Where and when is the final app built?

[LicensePlist](https://github.com/mono0926/LicensePlist#integrate-into-build) actually recommends having a build phase for debug builds. Is this fine as well?

**Comment by fbernutz** [comment]
The app is built locally from my machine, so having a build phase is fine in my opinion. 
I actually don't like that updating the Swift Packages has to be done in Xcode (can't be triggered with the update dependencies script) but it makes sense to Build in Xcode afterwards and it would generate the new License content.

**Comment by xavierLowmiller** [comment]
> having a build phase is fine in my opinion

This requires LicensePlist to be installed locally, but this can be done like with SwiftLint, so that it's skipped if the program isn't there.

> it can't be triggered with the update dependencies script, right?

[Seems to be the case][1]. I wouldn't worry about it though, because SPM dependency resolution should take the latest version that is compatible with the settings (`.upToNextMajor`, etc.)

[1]: https://stackoverflow.com/questions/58755069/how-to-trigger-xcodes-update-to-latest-package-versions-from-command-line

**Comment by xavierLowmiller** [comment]
I added the license-plist only for release builds to avoid GitHub's rate limiting

**Comment by fbernutz** [comment]
I fixed a segmentation fault in the script, but now it looks good to me 🎉 Let's merge this!

**Pull request merged**
