### PR TITLE
Remove Google Nearby

### PR DESCRIPTION
**Pull request by fbernutz**
# Description

With iOS 13 Google Nearby doesn't detect other nearby devices anymore and the library is also not updated within one and a half years which is very questionable for a library which requires access to bluetooth, microphone and location services.

This sadly removes the functionality to find a movie for a movie night with your friends nearby, which was a main part of the app before. The Android App has also issues with this feature, so, it doesn't make sense to keep it. 

The app is now not longer asking for permission for bluetooth, microphone or location services which feels great 🙂

## Checklist
- [x] Update `README.md`, if necessary \
  (e.g. when adding a new dependency, updating Swift Version, adding new language support)
- [x] Add an entry (formatted like the others) on Upcoming Release in `CHANGELOG.md`

### CODE REVIEW

**Comment by xavierLowmiller** [comment]
This might enable ditching cocoapods in favor of swift package manager 🎉

**Comment by fbernutz** [comment]
> This might enable ditching cocoapods in favor of swift package manager 🎉

Yesss, I'm excited!

**Comment by ChristianNorbertBraun** [comment]
So sad that this feature has to go...

**Comment by xavierLowmiller** [comment]
I'd love to try [Multipeer Connectivity](https://developer.apple.com/documentation/multipeerconnectivity) for this.

**Comment by xavierLowmiller** [comment]
The app is now a mere 2.9 MB

**Pull request merged**
