### PR TITLE
Xcode 12 migration

### PR DESCRIPTION
**Pull request by xavierLowmiller**
## Description

- Update snapshot reference images
- Select Xcode 12 before running tests
- Perform Xcode migration (enable recommended warnings, etc.)

### CODE REVIEW

**Review by fbernutz — COMMENTED** [review]
Thanks for doing this! 
Looks like there is an issue on `SettingsViewController` with the large title which was a large title in iOS 13 but isn't anymore in iOS 14. Has there something changed in iOS 14?

**Comment by xavierLowmiller** [comment]
Works on my machine 🤐...

What device are you running it on?

I checked on both Xcode 11.7 and 12, using an iPhone SE 2:

**Comment by fbernutz** [comment]
I saw it in the PR in the changed screenshot that it looks different now 🤔

**Review by fbernutz — APPROVED** [review]
It's not that relevant that the screenshot displays the large title, so let's merge this

**Pull request merged**
